version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - |
        pip install -U pip
        pip install -r requirements.txt
  pre_build:
    on-failure: CONTINUE
    commands:
      - |
        mkdir -p cfn
        aws configure set default.region $AWS_REGION
        for template in ./check_template/*.yml; do
          echo "$template" | xargs -I% -t aws cloudformation validate-template --template-body file://%;
        done
  build:
    commands:
    on-failure: CONTINUE
      - |
      aws cloudformation package \
      --template-file cfn.yml \
      --s3-bucket $S3_BUCKET \
      --output-template-file cfn/packaged.yml

artifacts:
  files:
    - cfn/*
    - params/*
  discard-paths: yes
