version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - pip3 install --upgrade pip
      - pip3 install cfn-lint
      - pip3 install pydot
  build:
    on-failure: CONTINUE
    commands:
      - cfn-lint cfn/*.yaml; echo "test"
artifacts:
  files:
    - "**/*"
  discard-paths: yes
