AWSTemplateFormatVersion: 2010-09-09
Description: ECR

Resources:
  #ECR
  TodobackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: cloudtech/todobackend

Outputs:
  Repository:
    Value: !Ref TodobackendRepository
    Export:
      Name: RepositoryName
